### ISSUE TITLE
¿Convert subtitles format old xml?

### ISSUE THREAD

**Issue by MiClobiMC** [nlitsme/youtube_tool#5]
![convertsubtitles](https://user-images.githubusercontent.com/60762569/113500983-39efa280-94f0-11eb-8695-9e547c5c5542.JPG)

**Comment by nlitsme** [comment]
is that a question?  I am not sure what you are asking.

**Comment by MiClobiMC** [comment]
I would like that the subtitles that are extracted with the tool can be converted to xml the old format is that I use a program and it only reads old subtitles

**Comment by MiClobiMC** [comment]
xml timedtext 1.0

**Comment by MiClobiMC** [comment]
https://medium.com/@js_jrod/the-first-complete-guide-to-youtube-captions-f886e06f7d9d

**Comment by MiClobiMC** [comment]
Problem solved, sorry for the inconvenience
