### ISSUE TITLE
KeyError: 'contents' when downloading comments using "--comments"

### ISSUE THREAD

**Issue by CEOGavin** [nlitsme/youtube_tool#7]
**Command**
`python3 yttool.py --comments https://www.youtube.com/watch?v=DbZZD6J_AK0 > comments.txt`

**Video ID**
`DbZZD6J_AK0`

**Output**

> Traceback (most recent call last):
>   File "/Users/foteini/youtube_tool/yttool.py", line 1197, in <module>
>     main()
>   File "/Users/foteini/youtube_tool/yttool.py", line 1178, in main
>     cmt.recursecomments()
>   File "/Users/foteini/youtube_tool/yttool.py", line 461, in recursecomments
>     self.recursecomments(subcc, level + 1)
>   File "/Users/foteini/youtube_tool/yttool.py", line 448, in recursecomments
>     cmtlist, cc = self.extractcomments(js)
>   File "/Users/foteini/youtube_tool/yttool.py", line 528, in extractcomments
>     for c in p["contents"]:
> KeyError: 'contents'

**Comment by nlitsme** [comment]
I am looking into it.
There was another change to the youtube api, now the request requires a http header: `X-Youtube-Identity-Token`
the value of which is taken from the ytcfg dictionary: `ID_TOKEN`.

I have yet to figure out when ID_TOKEN is set, it seems I get it in my browser, but not yet in my tool.

**Comment by CEOGavin** [comment]
What if we manually define these values externally that the program could use?
There are browser plugins that can help you capture cookies and other metadata. The user could (temporarily) grab these values and provide it to the script? I have seen such implementations in the past. Plus, it's a 'quick fix'.

**Comment by nlitsme** [comment]
I think I solved it now, can you try my latest update?
