### ISSUE TITLE
I can't download comments

### ISSUE THREAD

**Issue by crocketman** [nlitsme/youtube_tool#9]
For example, I write:

> yttool -c "https://www.youtube.com/watch?v=O55aXe4Uw3w" > ~/Desktop/comments.txt

On terminal happens anything (I don't know if this is normal), and the archive comments.txt is created, however, it's completely empty.

I also tried running command with sudo but the result is the same.

**Comment by mireksochor** [comment]
Same here :( the output of comment command is empty.

**Comment by nlitsme** [comment]
the problem seems to be a change in how continuations work.  I will look into it.

**Comment by pixdoet** [comment]
The problem seems to be with comment_service_ajax being deprecated, in which case it might be a good idea to switch to using youtubei's comments, eg: `https://youtube.com/youtubei/v1/next?key=[KEY]`

**Comment by nlitsme** [comment]
I have updated yttool.  comments and playlist list now work again.

still need to repair the `--replay` option.
